lines = []
lines.append('')
lines.append('    def _run_propagation(')
lines.append('        self, risk_request: RiskPropagationRequest')
lines.append('    ) -> RiskPropagationResponse:')
lines.append('        """Run the existing Module 10 risk propagation engine."""')
lines.append('        try:')
lines.append('            response = self._risk_propagation_service.propagate(risk_request)')
lines.append('        except EntityNotFoundError:')
lines.append('            raise')
lines.append('        except ServiceUnavailable:')
lines.append('            logger.error("Ripple prediction: Neo4j unavailable during propagation")')
lines.append('            raise')
lines.append('        except Neo4jError as exc:')
lines.append('            logger.error(')
lines.append('                "Ripple prediction: Neo4j error during propagation",')
lines.append('                extra={"error": str(exc)},')
lines.append('            )')
lines.append('            raise')
lines.append('        except Exception as exc:')
lines.append('            logger.error(')
lines.append('                "Ripple prediction: unexpected error during propagation",')
lines.append('                extra={"error": str(exc)},')
lines.append('                exc_info=True,')
lines.append('            )')
lines.append('            raise RipplePredictionError(')
lines.append('                "Risk propagation failed due to an unexpected error"')
lines.append('            ) from exc')
lines.append('')
lines.append('        if not isinstance(response, RiskPropagationResponse):')
lines.append('            raise RipplePredictionError(')
lines.append('                "Risk propagation returned an unexpected result type"')
lines.append('            )')
lines.append('        return response')
with open("backend/app/services/ripple_prediction/ripple_prediction_service.py", "a", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")
print("Part 5 done")
