lines = []
lines.append('')
lines.append('    def _resolve_risk_score(')
lines.append('        self,')
lines.append('        request: WebSocketRipplePredictionRequest,')
lines.append('        node: object,')
lines.append('    ) -> float:')
lines.append('        """Determine the source risk score."""')
lines.append('        if request.risk_score is not None:')
lines.append('            return float(request.risk_score)')
lines.append('')
lines.append('        persisted = self._extract_persisted_risk_score(node)')
lines.append('        if persisted is not None:')
lines.append('            return persisted')
lines.append('')
lines.append('        logger.info(')
lines.append('            "Ripple prediction: no risk score provided or persisted; "')
lines.append('            "defaulting to 0.0",')
lines.append('            extra={"entity_id": request.entity_id},')
lines.append('        )')
lines.append('        return 0.0')
lines.append('')
lines.append('    @staticmethod')
lines.append('    def _extract_persisted_risk_score(node: object):')
lines.append('        """Extract the persisted risk_score from a graph node response."""')
lines.append('        properties = None')
lines.append('')
lines.append('        if hasattr(node, "properties"):')
lines.append('            candidate = getattr(node, "properties", None)')
lines.append('            if isinstance(candidate, dict):')
lines.append('                properties = candidate')
lines.append('        elif isinstance(node, dict):')
lines.append('            candidate = node.get("properties")')
lines.append('            if isinstance(candidate, dict):')
lines.append('                properties = candidate')
lines.append('            elif "risk_score" in node:')
lines.append('                properties = node')
lines.append('')
lines.append('        if not properties:')
lines.append('            return None')
lines.append('')
lines.append('        raw = properties.get("risk_score")')
lines.append('        if isinstance(raw, (int, float)) and not isinstance(raw, bool):')
lines.append('            return float(raw)')
lines.append('        return None')
with open("backend/app/services/ripple_prediction/ripple_prediction_service.py", "a", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")
print("Part 4 done")
