lines = []
lines.append('')
lines.append('    def _resolve_entity(self, entity_id: str) -> object:')
lines.append('        """Resolve the source entity node, raising if it does not exist."""')
lines.append('        try:')
lines.append('            node = self._graph_service.get_node_by_id(entity_id)')
lines.append('        except ServiceUnavailable:')
lines.append('            logger.error(')
lines.append('                "Ripple prediction: Neo4j unavailable during entity resolution",')
lines.append('                extra={"entity_id": entity_id},')
lines.append('            )')
lines.append('            raise')
lines.append('        except Neo4jError as exc:')
lines.append('            logger.error(')
lines.append('                "Ripple prediction: Neo4j error during entity resolution",')
lines.append('                extra={"entity_id": entity_id, "error": str(exc)},')
lines.append('            )')
lines.append('            raise')
lines.append('        except Exception as exc:')
lines.append('            logger.error(')
lines.append('                "Ripple prediction: unexpected error during entity resolution",')
lines.append('                extra={"entity_id": entity_id, "error": str(exc)},')
lines.append('                exc_info=True,')
lines.append('            )')
lines.append('            raise RipplePredictionError(')
lines.append('                "Entity resolution failed due to an unexpected error"')
lines.append('            ) from exc')
lines.append('')
lines.append('        if node is None:')
lines.append('            logger.info(')
lines.append('                "Ripple prediction: source entity not found",')
lines.append('                extra={"entity_id": entity_id},')
lines.append('            )')
lines.append('            raise EntityNotFoundError(')
lines.append('                f"Entity \'{entity_id}\' not found in the graph"')
lines.append('            )')
lines.append('        return node')
with open("backend/app/services/ripple_prediction/ripple_prediction_service.py", "a", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")
print("Part 3 done")
