lines = []
lines.append('')
lines.append('    def _run_prediction(')
lines.append('        self, request: WebSocketRipplePredictionRequest')
lines.append('    ) -> Optional[list]:')
lines.append('        """Run the existing Module 14 GNN prediction for the current graph."""')
lines.append('        prediction_request = PredictionRequest(')
lines.append('            relationship_types=request.relationship_types,')
lines.append('        )')
lines.append('        try:')
lines.append('            response = self._prediction_service.get_predictions(prediction_request)')
lines.append('        except ModelNotAvailableError:')
lines.append('            logger.warning(')
lines.append('                "Ripple prediction: no GNN checkpoint configured; "')
lines.append('                "returning result without predictions",')
lines.append('            )')
lines.append('            return None')
lines.append('        except ServiceUnavailable:')
lines.append('            logger.error(')
lines.append('                "Ripple prediction: Neo4j unavailable during GNN prediction"')
lines.append('            )')
lines.append('            raise')
lines.append('        except GNNPredictionError as exc:')
lines.append('            logger.error(')
lines.append('                "Ripple prediction: GNN inference failed",')
lines.append('                extra={"error": str(exc)},')
lines.append('            )')
lines.append('            raise')
lines.append('        except Exception as exc:')
lines.append('            logger.error(')
lines.append('                "Ripple prediction: unexpected error during GNN prediction",')
lines.append('                extra={"error": str(exc)},')
lines.append('                exc_info=True,')
lines.append('            )')
lines.append('            raise RipplePredictionError(')
lines.append('                "GNN prediction failed due to an unexpected error"')
lines.append('            ) from exc')
lines.append('')
lines.append('        return list(response.predictions) if response.predictions else []')
with open("backend/app/services/ripple_prediction/ripple_prediction_service.py", "a", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")
print("Part 6 done")
