lines = []
lines.append('')
lines.append('    def _build_result(')
lines.append('        self,')
lines.append('        propagation: RiskPropagationResponse,')
lines.append('        predictions: Optional[list],')
lines.append('    ) -> RipplePredictionResult:')
lines.append('        """Build the final structured result from propagation + predictions."""')
lines.append('        prediction_map: dict[str, float] = {}')
lines.append('        if predictions:')
lines.append('            for pred in predictions:')
lines.append('                prediction_map[pred.node_id] = pred.prediction')
lines.append('')
lines.append('        affected_entities = [')
lines.append('            RippleAffectedEntity(')
lines.append('                entity_id=aff.entity_id,')
lines.append('                entity_name=aff.entity_name,')
lines.append('                depth=aff.depth,')
lines.append('                propagated_risk_score=aff.propagated_risk_score,')
lines.append('                propagated_risk_level=aff.propagated_risk_level,')
lines.append('                gnn_prediction=prediction_map.get(aff.entity_id),')
lines.append('            )')
lines.append('            for aff in propagation.affected_entities')
lines.append('        ]')
lines.append('')
lines.append('        prediction_count = sum(')
lines.append('            1 for ae in affected_entities if ae.gnn_prediction is not None')
lines.append('        )')
lines.append('')
lines.append('        return RipplePredictionResult(')
lines.append('            source_entity_id=propagation.source_entity_id,')
lines.append('            source_entity_name=propagation.source_entity_name,')
lines.append('            source_risk_score=propagation.source_risk_score,')
lines.append('            propagated=propagation.propagated,')
lines.append('            affected_entities=affected_entities,')
lines.append('            affected_count=propagation.affected_count,')
lines.append('            max_depth_reached=propagation.max_depth_reached,')
lines.append('            prediction_count=prediction_count,')
lines.append('            timestamp=datetime.now(timezone.utc),')
lines.append('            error=propagation.error,')
lines.append('        )')
lines.append('')
with open("backend/app/services/ripple_prediction/ripple_prediction_service.py", "a", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")
print("Part 7 done")
