import os

os.makedirs('backend/app/services/ripple_prediction', exist_ok=True)

lines = []
lines.append('"""Ripple prediction service for AtmoGraph (Module 17, Part 3).')
lines.append('')
lines.append('Orchestrates the existing risk propagation and GNN prediction services to')
lines.append("compute the ripple effect of a source entity's disruption through the supply")
lines.append('chain. This is a TRANSPORT-AGNOSTIC business layer: it returns a structured')
lines.append('Python result and knows nothing about WebSocket connections.')
lines.append('"""')
lines.append('')
lines.append('from __future__ import annotations')
lines.append('')
lines.append('from datetime import datetime, timezone')
lines.append('from typing import Optional')
lines.append('')
lines.append('from neo4j.exceptions import Neo4jError, ServiceUnavailable')
lines.append('')
lines.append('from app.core.logger import get_logger')
lines.append('from app.ml.exceptions import GNNPredictionError')
lines.append('from app.schemas.prediction import PredictionRequest')
lines.append('from app.schemas.risk_propagation import (')
lines.append('    RiskPropagationRequest,')
lines.append('    RiskPropagationResponse,')
lines.append(')')
lines.append('from app.schemas.websocket import WebSocketRipplePredictionRequest')
lines.append('from app.services.graph_service import GraphService')
lines.append('from app.services.prediction_service import ModelNotAvailableError, PredictionService')
lines.append('from app.services.risk.exceptions import EntityNotFoundError')
lines.append('from app.services.ripple_prediction.exceptions import RipplePredictionError')
lines.append('from app.services.ripple_prediction.result_schema import (')
lines.append('    RippleAffectedEntity,')
lines.append('    RipplePredictionResult,')
lines.append(')')
lines.append('from app.services.risk_propagation.risk_propagation_service import (')
lines.append('    RiskPropagationService,')
lines.append(')')
lines.append('')
lines.append('logger = get_logger(__name__)')
lines.append('')
lines.append('')
lines.append('')
lines.append('class RipplePredictionService:')
lines.append('    """Compute the ripple effect of a source entity\'s risk (Module 17).')
lines.append('')
lines.append('    Accepts a validated WebSocketRipplePredictionRequest, resolves the source')
lines.append('    entity through the existing graph layer, propagates its risk downstream')
lines.append('    using the existing Module 10 engine, and enriches the affected entities')
lines.append('    with real GNN predictions from the existing Module 14 pipeline.')
lines.append('')
lines.append('    External callers (the future WebSocket layer) use this service. It never')
lines.append('    touches a WebSocket and never invents data.')
lines.append('    """')
lines.append('')
lines.append('    def __init__(')
lines.append('        self,')
lines.append('        graph_service: Optional[GraphService] = None,')
lines.append('        risk_propagation_service: Optional[RiskPropagationService] = None,')
lines.append('        prediction_service: Optional[PredictionService] = None,')
lines.append('    ) -> None:')
lines.append('        self._graph_service = graph_service or GraphService()')
lines.append('        self._risk_propagation_service = (')
lines.append('            risk_propagation_service or RiskPropagationService()')
lines.append('        )')
lines.append('        self._prediction_service = prediction_service or PredictionService()')
lines.append('')
lines.append('    def predict(')
lines.append('        self, request: WebSocketRipplePredictionRequest')
lines.append('    ) -> RipplePredictionResult:')
lines.append('        """Compute the ripple prediction for a source entity.')
lines.append('')
lines.append('        Args:')
lines.append('            request: A validated WebSocketRipplePredictionRequest carrying at')
lines.append('                least the source entity_id.')
lines.append('')
lines.append('        Returns:')
lines.append('            A structured RipplePredictionResult containing the affected')
lines.append('            entities (from the real Module 10 propagation) enriched with')
lines.append('            real GNN predictions (from the real Module 14 pipeline).')
lines.append('')
lines.append('        Raises:')
lines.append('            EntityNotFoundError: The source entity does not exist.')
lines.append('            ServiceUnavailable: Neo4j is unreachable.')
lines.append('            ModelNotAvailableError: No trained GNN checkpoint configured.')
lines.append('            GNNPredictionError: GNN inference fails.')
lines.append('            RipplePredictionError: Unexpected internal failure.')
lines.append('        """')
lines.append('        entity_id = request.entity_id')
lines.append('')
lines.append('        # 1. Resolve the source entity BEFORE propagation so an unknown')
lines.append('        # entity fails fast without touching the propagation / GNN stack.')
lines.append('        node = self._resolve_entity(entity_id)')
lines.append('')
lines.append('        # 2. Determine the source risk score (request-supplied wins).')
lines.append('        risk_score = self._resolve_risk_score(request, node)')
lines.append('')
lines.append('        # 3. Propagate risk downstream using the existing Module 10 engine.')
lines.append('        propagation = self._propagate(request, risk_score)')
lines.append('')
lines.append('        # 4. Enrich affected entities with real GNN predictions.')
lines.append('        predictions = self._predict(request)')
lines.append('')
lines.append('        # 5. Build the structured result.')
lines.append('        result = self._build_result(propagation, predictions)')
lines.append('')
lines.append('        logger.info(')
lines.append('            "Ripple prediction computed",')
lines.append('            extra={')
lines.append('                "source_entity_id": result.source_entity_id,')
lines.append('                "affected_count": result.affected_count,')
lines.append('                "prediction_count": result.prediction_count,')
lines.append('                "propagated": result.propagated,')
lines.append('            },')
lines.append('    def _resolve_entity(self, entity_id: str) -> object:')
lines.append('        """Resolve the source entity node, raising if it does not exist."""')
lines.append('        try:')
lines.append('            node = self._graph_service.get_node_by_id(entity_id)')
lines.append('        except ServiceUnavailable:')
lines.append('            logger.error(')
lines.append('                "Ripple prediction: Neo4j unavailable during entity resolution",')
lines.append('                extra={"entity_id": entity_id},')
lines.append('            )')
lines.append('            raise')
lines.append('        except Neo4jError as exc:')
lines.append('            logger.error(')
lines.append('                "Ripple prediction: Neo4j error during entity resolution",')
lines.append('                extra={"entity_id": entity_id, "error": str(exc)},')
lines.append('            )')
lines.append('            raise')
lines.append('        except Exception as exc:')
lines.append('            logger.error(')
lines.append('                "Ripple prediction: unexpected error during entity resolution",')
lines.append('                extra={"entity_id": entity_id, "error": str(exc)},')
lines.append('                exc_info=True,')
lines.append('            )')
lines.append('            raise RipplePredictionError(')
lines.append('                "Entity resolution failed due to an unexpected error"')
lines.append('            ) from exc')
lines.append('')
lines.append('        if node is None:')
lines.append('            logger.info(')
lines.append('                "Ripple prediction: source entity not found",')
lines.append('                extra={"entity_id": entity_id},')
lines.append('            )')
lines.append('            raise EntityNotFoundError(')
lines.append('                f"Entity \'{entity_id}\' not found in the graph"')
lines.append('            )')
lines.append('        return node')
lines.append('')
lines.append('    def _resolve_risk_score(')
lines.append('        self,')
lines.append('        request: WebSocketRipplePredictionRequest,')
lines.append('        node: object,')
lines.append('    ) -> float:')
lines.append('        """Determine the source risk score.')
lines.append('')
lines.append('        Prefers the request-supplied score. When omitted, falls back to the')
lines.append("        entity's persisted risk_score property. If neither is available,")
lines.append('        defaults to 0.0 (LOW) - never invents a non-zero risk.')
lines.append('        """')
lines.append('        if request.risk_score is not None:')
lines.append('            return float(request.risk_score)')
lines.append('')
lines.append('        persisted = self._extract_persisted_risk_score(node)')
lines.append('        if persisted is not None:')
lines.append('            return persisted')
lines.append('')
lines.append('        logger.info(')
lines.append('            "Ripple prediction: no risk score provided or persisted; "')
lines.append('            "defaulting to 0.0",')
lines.append('            extra={"entity_id": request.entity_id},')
lines.append('        )')
lines.append('        return 0.0')
lines.append('')
lines.append('    @staticmethod')
lines.append('    def _extract_persisted_risk_score(node: object) -> Optional[float]:')
lines.append('        """Extract the persisted risk_score from a graph node response."""')
lines.append('        properties: Optional[dict] = None')
lines.append('')
lines.append('        if hasattr(node, "properties"):')
lines.append('            candidate = getattr(node, "properties", None)')
lines.append('            if isinstance(candidate, dict):')
lines.append('                properties = candidate')
lines.append('        elif isinstance(node, dict):')
lines.append('            candidate = node.get("properties")')
lines.append('    def _propagate(')
lines.append('        self,')
lines.append('        request: WebSocketRipplePredictionRequest,')
lines.append('        risk_score: float,')
lines.append('    ) -> RiskPropagationResponse:')
lines.append('        """Run the existing Module 10 risk propagation."""')
lines.append('        propagation_request = RiskPropagationRequest(')
lines.append('            entity_id=request.entity_id,')
lines.append('            entity_name=request.entity_name,')
lines.append('            risk_score=risk_score,')
lines.append('            max_depth=request.max_depth,')
lines.append('            attenuation=request.attenuation,')
lines.append('            relationship_types=request.relationship_types,')
lines.append('        )')
lines.append('')
lines.append('        try:')
lines.append('            propagation = self._risk_propagation_service.propagate(')
lines.append('                propagation_request')
lines.append('            )')
lines.append('        except ServiceUnavailable:')
lines.append('            logger.error(')
lines.append('                "Ripple prediction: Neo4j unavailable during propagation",')
lines.append('                extra={"entity_id": request.entity_id},')
lines.append('            )')
lines.append('            raise')
lines.append('        except EntityNotFoundError:')
lines.append('            logger.error(')
lines.append('                "Ripple prediction: source entity not found during propagation",')
lines.append('                extra={"entity_id": request.entity_id},')
lines.append('            )')
lines.append('            raise')
lines.append('        except Exception as exc:')
lines.append('            logger.error(')
lines.append('                "Ripple prediction: unexpected error during propagation",')
lines.append('                extra={"entity_id": request.entity_id, "error": str(exc)},')
lines.append('                exc_info=True,')
lines.append('            )')
lines.append('            raise RipplePredictionError(')
lines.append('                "Risk propagation failed due to an unexpected error"')
lines.append('            ) from exc')
lines.append('')
lines.append('        if not isinstance(propagation, RiskPropagationResponse):')
lines.append('            logger.error(')
lines.append('                "Ripple prediction: propagation returned an unexpected result type",')
lines.append('                extra={')
lines.append('                    "entity_id": request.entity_id,')
lines.append('                    "result_type": type(propagation).__name__,')
lines.append('                },')
lines.append('            )')
lines.append('            raise RipplePredictionError(')
lines.append('                "Risk propagation returned an unexpected result type"')
lines.append('            )')
lines.append('    def _predict(')
lines.append('        self,')
lines.append('        request: WebSocketRipplePredictionRequest,')
lines.append('    ) -> Optional[list]:')
lines.append('        """Run the existing Module 14 GNN prediction for the current graph.')
lines.append('')
lines.append('        Returns a list of NodePrediction entries, or None when prediction is')
lines.append('        unavailable (e.g. no checkpoint configured). Returns None instead of')
lines.append('        raising when the model is simply not deployed.')
lines.append('        """')
lines.append('        prediction_request = PredictionRequest(')
lines.append('            relationship_types=request.relationship_types,')
lines.append('        )')
lines.append('        try:')
lines.append('            response = self._prediction_service.get_predictions(prediction_request)')
lines.append('        except ModelNotAvailableError:')
lines.append('            logger.warning(')
lines.append('                "Ripple prediction: no GNN checkpoint configured; "')
lines.append('                "returning result without predictions",')
lines.append('            )')
lines.append('            return None')
lines.append('        except ServiceUnavailable:')
lines.append('            logger.error(')
lines.append('                "Ripple prediction: Neo4j unavailable during GNN prediction"')
lines.append('            )')
lines.append('            raise')
lines.append('        except GNNPredictionError as exc:')
lines.append('            logger.error(')
lines.append('                "Ripple prediction: GNN inference failed",')
lines.append('                extra={"error": str(exc)},')
lines.append('            )')
lines.append('            raise')
lines.append('        except Exception as exc:')
lines.append('            logger.error(')
lines.append('                "Ripple prediction: unexpected error during GNN prediction",')
lines.append('                extra={"error": str(exc)},')
lines.append('                exc_info=True,')
lines.append('            )')
lines.append('            raise RipplePredictionError(')
lines.append('                "GNN prediction failed due to an unexpected error"')
lines.append('            ) from exc')
lines.append('')
lines.append('        return list(response.predictions) if response.predictions else []')
lines.append('')
lines.append('    def _build_result(')
lines.append('        self,')
lines.append('        propagation: RiskPropagationResponse,')
lines.append('        predictions: Optional[list],')
lines.append('    ) -> RipplePredictionResult:')
lines.append('        """Build the final structured result from propagation + predictions.')
lines.append('')
lines.append('        Enriches each affected entity with the matching GNN prediction (by')
lines.append('        node_id). Entities without a matching prediction get')
lines.append('        ``gnn_prediction=None`` - nothing is invented.')
lines.append('        """')
lines.append('        prediction_map: dict[str, float] = {}')
lines.append('        if predictions:')
lines.append('            for pred in predictions:')
lines.append('                prediction_map[pred.node_id] = pred.prediction')
lines.append('')
lines.append('        affected_entities = [')
lines.append('            RippleAffectedEntity(')
lines.append('                entity_id=aff.entity_id,')
lines.append('                entity_name=aff.entity_name,')
lines.append('                depth=aff.depth,')
lines.append('                propagated_risk_score=aff.propagated_risk_score,')
lines.append('                propagated_risk_level=aff.propagated_risk_level,')
lines.append('                gnn_prediction=prediction_map.get(aff.entity_id),')
lines.append('            )')
lines.append('            for aff in propagation.affected_entities')
lines.append('        ]')
lines.append('')
lines.append('        prediction_count = sum(')
lines.append('            1 for ae in affected_entities if ae.gnn_prediction is not None')
lines.append('        )')
lines.append('')
lines.append('        return RipplePredictionResult(')
lines.append('            source_entity_id=propagation.source_entity_id,')
lines.append('            source_entity_name=propagation.source_entity_name,')
lines.append('            source_risk_score=propagation.source_risk_score,')
lines.append('            propagated=propagation.propagated,')
lines.append('            affected_entities=affected_entities,')
lines.append('            affected_count=propagation.affected_count,')
lines.append('            max_depth_reached=propagation.max_depth_reached,')
lines.append('            prediction_count=prediction_count,')
lines.append('            timestamp=datetime.now(timezone.utc),')
lines.append('            error=propagation.error,')
lines.append('        )')
lines.append('')
lines.append("with open('backend/app/services/ripple_prediction/ripple_prediction_service.py', 'w') as f:")
lines.append("    f.write('\\n'.join(lines))")
lines.append("    f.write('\\n')")
lines.append('')
lines.append('print("File written successfully")')

lines.append('')
lines.append('        return propagation')
lines.append('')

lines.append('            if isinstance(candidate, dict):')
lines.append('                properties = candidate')
lines.append('            elif "risk_score" in node:')
lines.append('                properties = node')
lines.append('')
lines.append('        if not properties:')
lines.append('            return None')
lines.append('')
lines.append('        raw = properties.get("risk_score")')
lines.append('        if isinstance(raw, (int, float)) and not isinstance(raw, bool):')
lines.append('            return float(raw)')
lines.append('        return None')
lines.append('')

lines.append('        )')
lines.append('        return result')
lines.append('')

lines.append('__all__ = [')
lines.append('    "RipplePredictionError",')
lines.append('    "RipplePredictionService",')
lines.append(')')
